name: OZ
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - appnope=0.1.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - automat=20.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.4.13
  - cairo=1.14.12
  - certifi=2020.12.5
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - colorama=0.4.4
  - constantly=15.1.0
  - cryptography=3.4.4
  - cssselect=1.1.0
  - curl=7.67.0
  - cycler=0.10.0
  - dbus=1.13.18
  - docutils=0.16
  - entrypoints=0.3
  - expat=2.2.10
  - fiona=1.8.4
  - flask=1.1.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.6
  - gdal=2.3.3
  - geopandas=0.6.1
  - gettext=0.21.0
  - giflib=5.1.4
  - glib=2.63.1
  - hdf4=4.2.13
  - hdf5=1.10.4
  - hyperlink=21.0.0
  - icu=58.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - incremental=17.5.0
  - iniconfig=1.1.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - itemadapter=0.2.0
  - itemloaders=1.0.4
  - itsdangerous=1.1.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - jmespath=0.10.0
  - jpeg=9d
  - json-c=0.13.1
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_console=6.2.0
  - jupyter_contrib_core=0.3.3
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=4.7.1
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kealib=1.4.7
  - kiwisolver=1.3.1
  - krb5=1.16.4
  - lcms2=2.12
  - libboost=1.67.0
  - libclang=11.0.1
  - libcurl=7.67.0
  - libcxx=11.0.1
  - libdap4=3.19.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgdal=2.3.3
  - libgfortran=3.0.1
  - libiconv=1.16
  - libkml=1.3.0
  - libllvm11=11.0.1
  - libnetcdf=4.6.1
  - libopenblas=0.3.13
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=4.3.0a
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.10
  - libxslt=1.1.34
  - llvm-openmp=11.0.1
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - more-itertools=8.7.0
  - munch=2.5.0
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbconvert=6.0.7
  - ncurses=6.2
  - nspr=4.29
  - nss=3.47
  - numpy-base=1.20.1
  - oauthlib=3.0.1
  - olefile=0.46
  - openjpeg=2.3.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandoc=2.11.4
  - parsel=1.6.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.0.1
  - pixman=0.40.0
  - pluggy=0.13.1
  - poppler=0.65.0
  - poppler-data=0.4.10
  - proj4=5.2.0
  - prompt_toolkit=3.0.16
  - protego=0.1.16
  - psycopg2=2.8.4
  - ptyprocess=0.7.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pydispatcher=2.0.5
  - pyhamcrest=2.0.2
  - pyjwt=2.0.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=1.9.6
  - pyqt=5.9.2
  - pyqt5-sip=4.19.18
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.8.2
  - python-dateutil=2.8.1
  - python-dotenv=0.15.0
  - python_abi=3.8
  - pytz=2021.1
  - pyyaml=5.4.1
  - qgrid=1.3.1
  - qt=5.9.7
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - queuelib=1.5.0
  - readline=7.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rtree=0.9.7
  - scrapy=2.4.1
  - send2trash=1.5.0
  - service_identity=18.1.0
  - setuptools=49.6.0
  - sip=4.19.8
  - six=1.15.0
  - soupsieve=2.0.1
  - sphinx_rtd_theme=0.5.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - sqlite=3.33.0
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.2
  - tornado=6.1
  - traitlets=5.0.5
  - tweepy=3.10.0
  - twisted=20.3.0
  - w3lib=1.22.0
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.3
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.4.0
  - zlib=1.2.11
  - zope.interface=5.2.0
  - zstd=1.4.8
  - pip:
    - absl-py==0.9.0
    - addict==2.4.0
    - affine==2.3.0
    - aiofiles==0.5.0
    - aldjemy==1.0.0
    - alembic==1.5.8
    - altair==4.1.0
    - aniso8601==7.0.0
    - anyio==3.4.0
    - appdirs==1.4.4
    - appscript==1.1.2
    - arrow==1.0.3
    - arviz==0.9.0
    - asgiref==3.3.1
    - astor==0.8.1
    - astunparse==1.6.3
    - async-exit-stack==1.0.1
    - babel==2.8.0
    - base58==2.1.0
    - binaryornot==0.4.4
    - black==20.8b1
    - bokeh==2.3.1
    - branca==0.4.2
    - brotli==1.0.7
    - build==0.3.1.post1
    - cachecontrol==0.12.6
    - cachetools==4.1.0
    - cachy==0.3.0
    - cartopy==0.18.0
    - cffi==1.14.5
    - cftime==1.1.3
    - check-manifest==0.46
    - cleo==0.8.1
    - clikit==0.6.2
    - commonmark==0.9.1
    - confuse==1.4.0
    - contextily==1.1.0
    - cookiecutter==1.7.2
    - coverage==5.5
    - crashtest==0.3.1
    - cython==0.29.17
    - dash==1.12.0
    - dash-core-components==1.10.0
    - dash-html-components==1.0.3
    - dash-renderer==1.4.1
    - dash-table==4.7.0
    - dbnomics==1.2.1
    - decorator==5.0.5
    - defusedxml==0.7.1
    - demjson==2.2.4
    - descartes==1.1.0
    - distlib==0.3.1
    - django==3.1.6
    - django-extensions==3.1.1
    - dnspython==1.16.0
    - docopt==0.6.2
    - docx2txt==0.8
    - docxcompose==1.3.1
    - dynaconf==3.1.4
    - email-validator==1.1.2
    - emoji==1.2.0
    - empyrical-dist==0.2.0
    - esbonio==0.5.0
    - et-xmlfile==1.0.1
    - faker==6.6.3
    - fastapi==0.63.0
    - fastprogress==0.2.3
    - fett==0.3.2
    - filelock==3.0.12
    - flask-compress==1.5.0
    - flask-cors==3.0.10
    - folium==0.12.1
    - fpdf==1.7.2
    - future==0.18.2
    - gast==0.3.3
    - gekko==0.2.6
    - geoalchemy2==0.8.5
    - geographiclib==1.50
    - geoplot==0.4.1
    - geopy==2.1.0
    - geos==0.2.3
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-api-core==1.26.0
    - google-api-python-client==2.2.0
    - google-auth==1.26.1
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - google-trans-new==1.1.9
    - googleapis-common-protos==1.52.0
    - googletrans==4.0.0rc1
    - graphene==2.1.8
    - graphql-core==2.3.2
    - graphql-relay==2.0.1
    - greenlet==1.0.0
    - grpcio==1.28.1
    - h11==0.9.0
    - h2==3.2.0
    - h5py==2.10.0
    - hpack==3.0.0
    - hstspreload==2020.12.22
    - html2text==2020.1.16
    - html5lib==1.1
    - htmlmin==0.1.12
    - httpcore==0.9.1
    - httplib2==0.19.0
    - httptools==0.1.1
    - httpx==0.13.3
    - hyperframe==5.2.0
    - imagehash==4.2.0
    - ipyaggrid==0.2.1
    - ipykernel==5.5.3
    - ipython==7.22.0
    - jdcal==1.4.1
    - jinja2-time==0.2.0
    - joblib==0.14.1
    - json5==0.9.6
    - jupyter-client==6.1.12
    - jupyter-server==1.12.1
    - jupyterlab==3.2.4
    - jupyterlab-server==2.8.2
    - justpy==0.1.5
    - keras==2.4.2
    - keras-preprocessing==1.1.1
    - keyring==21.8.0
    - libpysal==4.4.0
    - livereload==2.6.3
    - llvmlite==0.35.0
    - lockfile==0.12.2
    - lxml==4.6.3
    - mako==1.1.4
    - mapclassify==2.4.2
    - markdown==3.2.2
    - markdown-it-py==0.6.2
    - markdown2==2.4.0
    - matplotlib==3.4.1
    - mdit-py-plugins==0.2.5
    - mercantile==1.2.1
    - missingno==0.4.2
    - msgpack==1.0.2
    - mypy-extensions==0.4.3
    - myst-parser==0.13.5
    - nbclassic==0.3.4
    - nbclient==0.5.3
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - netcdf4==1.5.3
    - networkx==2.5
    - newsapi-python==0.2.6
    - nltk==3.5
    - notebook==6.3.0
    - numba==0.52.0
    - numpy==1.20.2
    - openpyxl==3.0.6
    - opt-einsum==3.2.1
    - orjson==3.4.8
    - ozcore==1.1.11
    - pandas==1.2.3
    - pandas-datareader==0.9.0
    - pandas-profiling==2.10.1
    - pandas-read-xml==0.1.0
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pastel==0.2.1
    - pathspec==0.8.1
    - patsy==0.5.1
    - pdfkit==0.6.1
    - pep517==0.10.0
    - phik==0.11.0
    - pillow==8.2.0
    - pkginfo==1.7.0
    - plotly==4.7.1
    - pmdarima==1.6.1
    - pockets==0.9.1
    - poetry-core==1.0.2
    - poyo==0.5.0
    - prometheus-client==0.10.0
    - promise==2.3
    - prompt-toolkit==3.0.18
    - protobuf==3.14.0
    - pyarrow==3.0.0
    - pydantic==1.7.3
    - pydataset==0.2.0
    - pydeck==0.6.2
    - pygeos==0.9
    - pygls==0.9.1
    - pygments==2.8.1
    - pygoogletranslation==2.0.6
    - pylev==1.3.0
    - pymc3==3.9.2
    - pymongo==3.11.3
    - pypdf2==1.26.0
    - pyshp==2.1.3
    - pytest-cov==2.11.1
    - pytest-remotedata==0.3.2
    - python-docx==0.8.10
    - python-editor==1.0.4
    - python-jsonrpc-server==0.3.4
    - python-multipart==0.0.5
    - python-pptx==0.6.18
    - python-slugify==4.0.1
    - pywavelets==1.1.1
    - pyzmq==22.0.3
    - rasterio==1.2.2
    - recommonmark==0.7.1
    - regex==2020.11.13
    - requests-toolbelt==0.9.1
    - retrying==1.3.3
    - rfc3986==1.4.0
    - rsa==4.0
    - rstcheck==3.3.1
    - rx==1.6.1
    - scikit-learn==0.23.0
    - scipy==1.6.1
    - seaborn==0.11.1
    - shapely==1.7.1
    - shellingham==1.4.0
    - simplejson==3.17.2
    - smmap==4.0.0
    - sniffio==1.2.0
    - snooty-lextudio==1.8.9.dev0
    - snowballstemmer==2.0.0
    - snuggs==1.4.7
    - sodapy==2.1.0
    - sphinx==3.5.2
    - sphinx-autobuild==2020.9.1
    - sphinxcontrib-napoleon==0.7
    - sqlalchemy==1.4.5
    - sqlparse==0.4.1
    - starlette==0.13.6
    - statsmodels==0.12.2
    - streamlit==0.80.0
    - tangled-up-in-unicode==0.0.6
    - tensorboard==2.2.1
    - tensorboard-plugin-wit==1.6.0.post3
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - terminado==0.9.4
    - text-unidecode==1.3
    - theano==1.0.4
    - threadpoolctl==2.0.0
    - tomlkit==0.7.0
    - toolz==0.11.1
    - tox==3.23.0
    - tqdm==4.60.0
    - typed-ast==1.4.2
    - typeguard==2.12.0
    - typer==0.3.2
    - typing==3.7.4.3
    - typing-extensions==3.7.4.2
    - tzlocal==2.1
    - ujson==1.35
    - unidecode==1.2.0
    - uritemplate==3.0.1
    - urllib3==1.26.4
    - uvicorn==0.13.4
    - uvloop==0.15.2
    - validators==0.18.2
    - vega-datasets==0.9.0
    - virtualenv==20.4.3
    - visions==0.6.0
    - watchdog==1.0.2
    - watchgod==0.7
    - websocket-client==1.2.1
    - websockets==8.1
    - wrapt==1.12.1
    - xarray==0.15.1
    - xlrd==1.2.0
    - xlsxwriter==1.2.8
    - xmltodict==0.12.0
    - zipfile36==0.1.3
